### ISSUE TITLE
Markdown Table Box disappears after adding custom toolbar

### ISSUE THREAD

**Issue by iG8R** [XiLaiTL/vscode-toolbar#2]
Actually, all the description is present in the title of the issue.
Here is the screencast.

https://github.com/user-attachments/assets/e82487c2-dd4a-4a51-b6f8-e02346365a3a

**Comment by XiLaiTL** [comment]
You need to add your custom things before or after the inner one in the same list (it should be remained). Like this:
```json
        "toolbar.toolboxs": [
            {
                "name": "Insert Text",
                "view": "mars",
                "activate":true,
                "layers": [
                    {
                        "name": "above",
                        "tools": [
                            {
                                "name": "test",
                                "actions": [{
                                    "command": "editor.action.insertSnippet",
                                    "argument":{
                                        "snippet": "console.log($1)$0"
                                    },
                                    "mode": "command"
                                }]
                            },      
                            {
                                "name": "other",
                                "actions": [{
                                    "command": "workbench.action.findInFiles",
                                    "argument":{
                                        "query":"no",
                                        "replace":"yes",
                                        "isRegex":true,
                                    },
                                    "mode": "command"
                                }]
                            }
                        ]
                    }
                ]
            },
            {
                "_comment": "Need <Markdown Table> by Takumi Ishii; <Markdown Table Maker> by hellorusk",
                "name": "Markdown Table Box",
                "view": "markdown",
                "activate": {
                    "hover": false,
                    "languages": [
                        "markdown"
                    ]
                },
                "layers": [
                    {
                        "name": "Cell",
                        "icon": "primitive-square",
                        "tools": [
                            {
                                "name": "Previous Cell",
                                "icon": "arrow-circle-left",
                                "actions": [
                                    "markdowntable.nextCell"
                                ]
                            },
                            {
                                "name": "Next Cell",
                                "icon": "arrow-circle-right",
                                "actions": [
                                    "markdowntable.prevCell"
                                ]
                            },
                            {
                                "name": "Create Table",
                                "icon": "symbol-number",
                                "actions": [
                                    "tablemaker.make"
                                ]
                            },
                            {
                                "name": "CSV To Table",
                                "icon": "project",
                                "actions": [
                                    "markdowntable.csvToTable"
                                ]
                            }
                        ]
                    },
                    {
                        "name": "Column",
                        "icon": "split-horizontal",
                        "tools": [
                            {
                                "name": "Move Left",
                                "icon": "arrow-small-left",
                                "actions": [
                                    "markdowntable.moveLeft"
                                ]
                            },
                            {
                                "name": "Move Right",
                                "icon": "arrow-small-right",
                                "actions": [
                                    "markdowntable.moveRight"
                                ]
                            },
                            {
                                "name": "Insert Left",
                                "icon": "chevron-left",
                                "actions": [
                                    "markdowntable.insertLeft"
                                ]
                            },
                            {
                                "name": "Insert Right",
                                "icon": "chevron-right",
                                "actions": [
                                    "markdowntable.insertRight"
                                ]
                            }
                        ]
                    },
                    {
                        "name": "Formatting",
                        "icon": "layout",
                        "tools": [
                            {
                                "name": "Align Left",
                                "icon": "debug-reverse-continue",
                                "actions": [
                                    "markdowntable.alignLeft"
                                ]
                            },
                            {
                                "name": "Align Right",
                                "icon": "debug-continue",
                                "actions": [
                                    "markdowntable.alignCenter"
                                ]
                            },
                            {
                                "name": "Align Center",
                                "icon": "debug-pause",
                                "actions": [
                                    "markdowntable.alignRight"
                                ]
                            },
                            {
                                "name": "Format",
                                "icon": "jersey",
                                "actions": [
                                    "markdowntable.format"
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
```

**Comment by iG8R** [comment]
Thanks for such a quick answer.
Then, why "Markdown Toolbox" didn't disappear after adding my toolboxes?
And also another question - why, when I work with the markdown document, the "Markdown Toolbox" tooltip pop ups when I selected some text, but "Markdown Table Box" doesn't?

**Comment by iG8R** [comment]
I inserted the following into settings.json
```
  "toolbar.toolboxs": [
    {
      "name": "Insert Text",
      "view": "mars",
      "activate": true,
      "layers": [
        {
          "name": "above",
          "tools": [
            {
              "name": "test",
              "actions": [
                {
                  "command": "editor.action.insertSnippet",
                  "argument": {
                    "snippet": "console.log($1)$0"
                  },
                  "mode": "command"
                }
              ]
            },
            {
              "name": "other",
              "actions": [
                {
                  "command": "workbench.action.findInFiles",
                  "argument": {
                    "query": "no",
                    "replace": "yes",
                    "isRegex": true
                  },
                  "mode": "command"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "_comment": "Need <Markdown Table> by Takumi Ishii; <Markdown Table Maker> by hellorusk",
      "name": "Markdown Table Box",
      "view": "markdown",
      "activate": {
        "hover": false,
        "languages": ["markdown"]
      },
      "layers": [
        {
          "name": "Cell",
          "icon": "primitive-square",
          "tools": [
            {
              "name": "Previous Cell",
              "icon": "arrow-circle-left",
              "actions": ["markdowntable.nextCell"]
            },
            {
              "name": "Next Cell",
              "icon": "arrow-circle-right",
              "actions": ["markdowntable.prevCell"]
            },
            {
              "name": "Create Table",
              "icon": "symbol-number",
              "actions": ["tablemaker.make"]
            },
            {
              "name": "CSV To Table",
              "icon": "project",
              "actions": ["markdowntable.csvToTable"]
            }
          ]
        },
        {
          "name": "Column",
          "icon": "split-horizontal",
          "tools": [
            {
              "name": "Move Left",
              "icon": "arrow-small-left",
              "actions": ["markdowntable.moveLeft"]
            },
            {
              "name": "Move Right",
              "icon": "arrow-small-right",
              "actions": ["markdowntable.moveRight"]
            },
            {
              "name": "Insert Left",
              "icon": "chevron-left",
              "actions": ["markdowntable.insertLeft"]
            },
            {
              "name": "Insert Right",
              "icon": "chevron-right",
              "actions": ["markdowntable.insertRight"]
            }
          ]
        },
        {
          "name": "Formatting",
          "icon": "layout",
          "tools": [
            {
              "name": "Align Left",
              "icon": "debug-reverse-continue",
              "actions": ["markdowntable.alignLeft"]
            },
            {
              "name": "Align Right",
              "icon": "debug-continue",
              "actions": ["markdowntable.alignCenter"]
            },
            {
              "name": "Align Center",
              "icon": "debug-pause",
              "actions": ["markdowntable.alignRight"]
            },
            {
              "name": "Format",
              "icon": "jersey",
              "actions": ["markdowntable.format"]
            }
          ]
        }
      ]
    },
    {
      "name": "My Box",
      "activate": true,
      "view": "markdown",
      "layers": [
        {
          "name": "My Layer",
          "icon": "person",
          "tools": [
            {
              "name": "Open Extensions Folder",
              "icon": "folder-library",
              "actions": ["workbench.extensions.action.openExtensionsFolder"]
            }
          ]
        }
      ]
    }
  ]
```

And got the following in a markdown file, despite the fact, that **"Markdown Table Box"** has **"hover": false** and **"My Box"** and **"Insert Text"** tool boxes have no "hover" option at all.
At the same time, in all other file types, e.g. **.json** or **.js**, the tooltips with **"My Box"** and **"Insert Text"** don't appear at all.
What is the principle behind the appearance of tooltips?
If the **"hover"** option is needed to make the tool box appear in the tooltip, then why **"My Box"** and **"Insert Text"** appear in the tooltip in the markdown file?
Conversely - if **"hover "** is not needed and its absence by default causes tool boxes to appear in the tooltip, why **"My Box"** and **"Insert text "** don't appear in all files?

![image](https://github.com/user-attachments/assets/50bda08f-70cc-4fa7-b0fa-18ffc9abc1f4)
![image](https://github.com/user-attachments/assets/0c8c2205-3c81-4abc-8e87-266c67d5bbfa)
![image](https://github.com/user-attachments/assets/3e8ee125-3a3e-4a8d-af2a-635ea056c696)

**Comment by XiLaiTL** [comment]
> Thanks for such a quick answer. Then, why "Markdown Toolbox" didn't disappear after adding my toolboxes? And also another question - why, when I work with the markdown document, the "Markdown Toolbox" tooltip pop ups when I selected some text, but "Markdown Table Box" doesn't?

Because "Markdown Toolbox" is built-in while "Markdown Table Box" relied on other extension. So I made it as a setting.

**Comment by XiLaiTL** [comment]
> I inserted the following into settings.json
> 
> ```
>   "toolbar.toolboxs": [
>     {
>       "name": "Insert Text",
>       "view": "mars",
>       "activate": true,
>       "layers": [
>         {
>           "name": "above",
>           "tools": [
>             {
>               "name": "test",
>               "actions": [
>                 {
>                   "command": "editor.action.insertSnippet",
>                   "argument": {
>                     "snippet": "console.log($1)$0"
>                   },
>                   "mode": "command"
>                 }
>               ]
>             },
>             {
>               "name": "other",
>               "actions": [
>                 {
>                   "command": "workbench.action.findInFiles",
>                   "argument": {
>                     "query": "no",
>                     "replace": "yes",
>                     "isRegex": true
>                   },
>                   "mode": "command"
>                 }
>               ]
>             }
>           ]
>         }
>       ]
>     },
>     {
>       "_comment": "Need <Markdown Table> by Takumi Ishii; <Markdown Table Maker> by hellorusk",
>       "name": "Markdown Table Box",
>       "view": "markdown",
>       "activate": {
>         "hover": false,
>         "languages": ["markdown"]
>       },
>       "layers": [
>         {
>           "name": "Cell",
>           "icon": "primitive-square",
>           "tools": [
>             {
>               "name": "Previous Cell",
>               "icon": "arrow-circle-left",
>               "actions": ["markdowntable.nextCell"]
>             },
>             {
>               "name": "Next Cell",
>               "icon": "arrow-circle-right",
>               "actions": ["markdowntable.prevCell"]
>             },
>             {
>               "name": "Create Table",
>               "icon": "symbol-number",
>               "actions": ["tablemaker.make"]
>             },
>             {
>               "name": "CSV To Table",
>               "icon": "project",
>               "actions": ["markdowntable.csvToTable"]
>             }
>           ]
>         },
>         {
>           "name": "Column",
>           "icon": "split-horizontal",
>           "tools": [
>             {
>               "name": "Move Left",
>               "icon": "arrow-small-left",
>               "actions": ["markdowntable.moveLeft"]
>             },
>             {
>               "name": "Move Right",
>               "icon": "arrow-small-right",
>               "actions": ["markdowntable.moveRight"]
>             },
>             {
>               "name": "Insert Left",
>               "icon": "chevron-left",
>               "actions": ["markdowntable.insertLeft"]
>             },
>             {
>               "name": "Insert Right",
>               "icon": "chevron-right",
>               "actions": ["markdowntable.insertRight"]
>             }
>           ]
>         },
>         {
>           "name": "Formatting",
>           "icon": "layout",
>           "tools": [
>             {
>               "name": "Align Left",
>               "icon": "debug-reverse-continue",
>               "actions": ["markdowntable.alignLeft"]
>             },
>             {
>               "name": "Align Right",
>               "icon": "debug-continue",
>               "actions": ["markdowntable.alignCenter"]
>             },
>             {
>               "name": "Align Center",
>               "icon": "debug-pause",
>               "actions": ["markdowntable.alignRight"]
>             },
>             {
>               "name": "Format",
>               "icon": "jersey",
>               "actions": ["markdowntable.format"]
>             }
>           ]
>         }
>       ]
>     },
>     {
>       "name": "My Box",
>       "activate": true,
>       "view": "markdown",
>       "layers": [
>         {
>           "name": "My Layer",
>           "icon": "person",
>           "tools": [
>             {
>               "name": "Open Extensions Folder",
>               "icon": "folder-library",
>               "actions": ["workbench.extensions.action.openExtensionsFolder"]
>             }
>           ]
>         }
>       ]
>     }
>   ]
> ```
> 
> And got the following in a markdown file, despite the fact, that **"Markdown Table Box"** has **"hover": false** and **"My Box"** and **"Insert Text"** tool boxes have no "hover" option at all. At the same time, in all other file types, e.g. **.json** or **.js**, the tooltips with **"My Box"** and **"Insert Text"** don't appear at all. What is the principle behind the appearance of tooltips? If the **"hover"** option is needed to make the tool box appear in the tooltip, then why **"My Box"** and **"Insert Text"** appear in the tooltip in the markdown file? Conversely - if **"hover "** is not needed and its absence by default causes tool boxes to appear in the tooltip, why **"My Box"** and **"Insert text "** don't appear in all files?
> 
> ![image](https://private-user-images.githubusercontent.com/11407417/359593783-50bda08f-70cc-4fa7-b0fa-18ffc9abc1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA4MjEsIm5iZiI6MTcyNDIxMDUyMSwicGF0aCI6Ii8xMTQwNzQxNy8zNTk1OTM3ODMtNTBiZGEwOGYtNzBjYy00ZmE3LWIwZmEtMThmZmM5YWJjMWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MTQzNTlkMGFjNjk1NjlhY2RiOTE3NmViM2YwMjc0ZGQ4MTQ2NDM2ZDU3NjU5MTA4ODk4OTBhOTJmODNhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BUTz4BNKyI7I5P7U8u9hvCLgNePWgOv-YVNjUHv2gXo) ![image](https://private-user-images.githubusercontent.com/11407417/359598644-0c8c2205-3c81-4abc-8e87-266c67d5bbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA4MjEsIm5iZiI6MTcyNDIxMDUyMSwicGF0aCI6Ii8xMTQwNzQxNy8zNTk1OTg2NDQtMGM4YzIyMDUtM2M4MS00YWJjLThlODctMjY2YzY3ZDViYmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OGZmOGNkOGE1MzA1NGI5ZTkzNWVmYmY4MGQ2NzZkNTQ5ZjkyZTU2NmNhOTRlZGI0NjgyYmQ3YWI2ZWY2YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_iJ9_X42PlNcDKIk294LR8KKOtgfhgcLgXHZ61EgfQ) ![image](https://private-user-images.githubusercontent.com/11407417/359598690-3e8ee125-3a3e-4a8d-af2a-635ea056c696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA4MjEsIm5iZiI6MTcyNDIxMDUyMSwicGF0aCI6Ii8xMTQwNzQxNy8zNTk1OTg2OTAtM2U4ZWUxMjUtM2EzZS00YThkLWFmMmEtNjM1ZWEwNTZjNjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NGI2N2I4NmY3ODJjZTY4ZjA0ZmJlYjBiYjBkMTE4MWUyNWE5MTc1MWQ4ZTExY2M1OTA3YmJjMWJkNzBkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UCH3SoYjVUvUS7TokQeUVEk5NmhVcBrj-gUj42pr7Fw)

You need to set it in settings, which can be found in setting page. (toolbar.hover.languages)

**Comment by iG8R** [comment]
> Because "Markdown Toolbox" is built-in while "Markdown Table Box" relied on other extension. So I made it as a setting.

Thank you for the clarification.
Is it possible to automatically insert the `Markdown Table Box` code into the settings.json file after installing Toolbar, since once the user code is added to that file, where can the user easily find the `Markdown Table Box` code?


> You need to set it in settings, which can be found in setting page. (toolbar.hover.languages)

So, in order to make the tooltip appear in one or another language, the user needs to perform the following actions:
1. In **Settings -> Extensions -> Toolbar -> Hover:Languages** is needed to add the desired language item, e.g. `markdown`, `json`, `jsonc`, `javascript` etc
2. then control the appearance of the tooltip in the corresponding language by inserting and modifying in the `settings.json` file the following code when defining the appropriate toolbox.
```
      "activate": {
        "hover": false, // or true
        "languages": ["markdown"]
      }
```
If there are many languages, then does the user need to insert them all into the "activate" field?
E.g. I have `toolbar.hover.languages` set with `markdown`, `json`, `jsonc`, `javascript` etc. And I want the tooltip for the toolbox `MyBox` appears only in `json`, `jsonc` files, then I need to add the following lines into the settings.json when defining `MyBox`?
```
      "activate": {
        "hover": false,
        "languages": ["markdown","javascript"]
      }
```
or
```
      "activate": {
        "hover": true,
        "languages": ["json","jsonc"]
      }
```
Are the both statements equal?

There is the **Settings -> Extensions -> Toolbar -> Panel:Languages** option, but I can not find any additional button to the right top of the corresponding language editor.
![image](https://github.com/user-attachments/assets/aaea3851-0c59-4ce3-afb1-5c7befa31276)

**Comment by iG8R** [comment]
![image](https://github.com/user-attachments/assets/0cbacca7-f058-494f-9339-c993dd6e061e)

Is there anything that can be done with these scrollbars so that they only appear when there really isn't enough space for them?

**Comment by XiLaiTL** [comment]
>where can the user easily find the Markdown Table Box code?

You first time edit the settings in setting page, it is in there by default.

**Comment by iG8R** [comment]
> You first time edit the settings in setting page, it is in there by default.

Unfortunately, no, initially there were no mentions of the Markdown Table Box code. It was only after I copied your code above that it appeared there. You can see it in the screencast from the first post.

**Comment by XiLaiTL** [comment]
> So, in order to make the tooltip appear in one or another language, the user needs to perform the following actions:
> 
> In Settings -> Extensions -> Toolbar -> Hover:Languages is needed to add the desired language item, e.g. markdown, json, jsonc, javascript etc
> then control the appearance of the tooltip in the corresponding language by inserting and modifying in the settings.json file the following code when defining the appropriate toolbox.
>       "activate": {
>         "hover": false, // or true
>         "languages": ["markdown"]
>       }
> If there are many languages, then does the user need to insert them all into the "activate" field?

Yes.
Anyway, you can try it yourself.

**Comment by XiLaiTL** [comment]
> > You first time edit the settings in setting page, it is in there by default.
> 
> Unfortunately, no, initially there were no mentions of the Markdown Table Box code. It was only after I copied your code above that it appeared there. You can see it in the screencast from the first post.

You can try, just delete your code which is in your `settings.json` now. And open the setting page (vscode page, no settings.json). 
![image](https://github.com/user-attachments/assets/bccd8397-a071-4a33-8a40-d6b66d9c679e)

**Comment by iG8R** [comment]
> You can try, just delete your code which is in your `settings.json` now. And open the setting page (vscode page, no settings.json).

Oh, I see. In that way it works.
But this feature is not reflected in the `readme.md` file.
There only settings.json file is mentioned.
Could you please add additional info there to clarify some points, also including `"activate" -> "hover"` matter?

![image](https://github.com/user-attachments/assets/cf7ceb3a-0e78-49a3-9115-32a4c8f2b0e7)
![image](https://github.com/user-attachments/assets/ad90f817-bf3e-42a6-91f7-36d214e562b2)

**Comment by XiLaiTL** [comment]
> Could you please add additional info there to clarify some points, also including `"activate" -> "hover"` matter?

Sure. If it is possible, you can change the `readme.md` and pull request to this project. I will appreciate it.

**Comment by iG8R** [comment]
> Sure. If it is possible, you can change the `readme.md` and pull request to this project. I will appreciate it.

Done :)

**Comment by iG8R** [comment]
Could anything be done with:

> There is the **Settings -> Extensions -> Toolbar -> Panel:Languages** option, but I can not find any additional button to the right top of the corresponding language editor.

and 

> Is there anything that can be done with these scrollbars so that they only appear when there really isn't enough space for them?
